symfony/src/Entity/Service.php
<?php

namespace App\Entity;

use App\Entity\Traits\GedmoTrait;
use App\Entity\Traits\AuthorableTrait;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\Validator\Constraints as Assert;
use Knp\DoctrineBehaviors\Model as ORMBehaviors;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ServiceRepository")
 * @ORM\Table(name="dk_service")
 * @ORM\HasLifecycleCallbacks
 * @Gedmo\SoftDeleteable(fieldName="deletedAt", timeAware=false)
 */
class Service
{
    use GedmoTrait;
    use AuthorableTrait;
    use ORMBehaviors\Translatable\Translatable;

    /**
     * Id
     *
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param mixed $id
     */
    public function setId($id)
    {
        $this->id = $id;
    }

    public function getName()
    {
        return $this->getTranslations()->first()->getName();
    }

    public function getDescription()
    {
        return $this->getTranslations()->first()->getDescription();
    }

    public function getNameCave()
    {
        return $this->getTranslations()->first()->getName().'::'.$this->getTranslations()->first()->getCave().'::'.$this->getTranslations()->first()->isServiceStandard();
    }
}

symfony/src/Controller/Front/CatalogController.php
<?php


/**
 * Admin controller for manager a module
 *
 * @author Adrien Jerphagnon <adrien.jerphagnon@disko.fr>
 */

namespace App\Controller\Front;

use App\Controller\BaseController;
use App\Entity\Project;
use App\Utils\Managers\CategoryManager;
use App\Utils\Managers\ProductManager;
use App\Utils\Managers\ProjectManager;
use App\Utils\Managers\StockLineManager;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Class CatalogController
 *
 * @Route("/")
 * @package App\Controller
 */
class CatalogController extends BaseController
{


    /**
     * Catalog
     * @Route("/catalogue", name="catalog")
     * @return Response
     */
    public function index(Request $request, ProductManager $productManager, ProjectManager $projectManager, StockLineManager $stockLineManager, CategoryManager $categoryManager)
    {
        $project = $this->get('session')->get('current_project', null);
        $stock = $this->get('session')->get('current_stock');


        $keyword = $request->get('keyword', null);
        $category = $request->get('category', null);
        $limit = $request->get('limit', null);

        if (!in_array($limit, [12, 24])) {
            $limit = 12;
        }

        $datas = $projectManager->getParameters($project);

        // Generate query
        $query = $productManager->queryForSearchInFront($stock, $datas['cave'], $keyword, $category, $project);

        // Paginate transform
        $paginator  = $this->get('knp_paginator');
        $pagination = $paginator->paginate(
            $query,
            $request->query->get('page', 1),
            $limit,
            array('wrap-queries'=>true)
        );

        $ids = [];
        $objects = [];
        foreach ($pagination as $product) {
            $ids[] = $product->getId();
            $objects[] = $product;
        }

        // Get stock (large view or specific view)
        $totalWithHolds = $total115WithHolds = $totalPantinWithHolds =null;
        if ($datas['cave']) {
            $totalWithHolds = $stockLineManager->totalStockOnProducts($stock, $datas['cave'], $ids, $datas['dateStart'], $datas['dateEnd'], true);

            if($datas['cave'] == Project::CAVE_PANTIN){
                $totalWithHolds = [];
                foreach($objects as $object){
                    $totalWithHolds[] = [
                        'total' => $stockLineManager->quantityOf($object, Project::CAVE_PANTIN, new \DateTime('now'), $stock, false),
                        'id' => $object->getId()
                    ];
                }
            }
        } else {
            $total115WithHolds = $stockLineManager->totalStockOnProducts($stock, Project::CAVE_115, $ids, $datas['dateStart'], $datas['dateEnd'], true);

            //$totalPantinWithHolds = $stockLineManager->totalStockOnProducts($stock, Project::CAVE_PANTIN, $ids, $datas['dateStart'], $datas['dateEnd'], true);
            $totalPantinWithHolds = [];
            foreach($objects as $object){
                $totalPantinWithHolds[] = [
                    'total' => $stockLineManager->quantityOf($object, Project::CAVE_PANTIN, new \DateTime('now'), $stock, false),
                    'id' => $object->getId()
                ];
            }
        }

        // Find all categories active
        $categories = $categoryManager->findAllActive();
        $categoriesCounts = $productManager->countProductsInCategories($stock, $project);


        $template = 'hub/catalog/index.html.twig';
        if ($keyword) {
            $template = 'hub/catalog/result.html.twig';
        }

        return $this->render($template, [
            'search' => [
                'keyword' => $keyword,
                'category' => $category,
                'limit' => $limit,
            ],
            'categories' => $categories,
            'categoriesCounts' => $categoriesCounts,
            'pagination' => $pagination,
            'totalWithHolds' => $totalWithHolds,
            'total115WithHolds' => $total115WithHolds,
            'totalPantinWithHolds' => $totalPantinWithHolds,
        ]);
    }
}

symfony/templates/hub/catalog/partials/_box.html.twig
<div class="product product--higher">
    <a href="{{ path('product_view', {slug: product.translate('fr').slug}) }}" class="product__image" style="background-image: url({% if product.translate('fr').cover is not empty and product.translate('fr').cover.path is not empty %}{{ asset( product.translate('fr').cover|ifs.path|imagine_filter(filter|default('hennessy_product_main'))) }}{% else %}//placehold.it/200x200{% endif %});">
        {% if product.translate('fr').state != "new" %}
            <span class="product__block" style="background-color: rgba(176, 128, 103, 0.9); color: #FFF;">
                <img class="svg" src="{{ asset('assets/front/images/info.svg') }}" alt="">
                <span>{{ 'app.product.states.out_of_use'|trans }}</span>
            </span>
        {% endif %}
    </a>

    <div class="product__content">
        <h6><a href="{{ path('product_view', {slug: product.translate('fr').slug}) }}">{{ product.translate('fr').name }}</a></h6>
        <p>{{ product.translate('fr').description }}</p>

        {% include "hub/product/partials/_stock.html.twig" %}

    </div><!-- /.product__content -->
</div><!-- /.product -->

symfony/templates/hub/catalog/partials/_filter.html.twig
<div class="filter">
    <p>Nombre de produits par page : </p>
    <ul class="list-filter">
        {% for limit in [12, 24] %}
            {% set path = path(app.request.attributes.get('_route'), app.request.attributes.get('_route_params')|merge(app.request.query.all)|merge({'limit': limit})) %}
            <li {% if search.limit == limit %}class="current" style="color: #2c455b" {% endif %}>
                <a {% if search.limit != limit %}href="{{ path }}"{% endif %}>{{ limit }}</a>
            </li>
        {% endfor %}
    </ul><!-- /.list-filter -->
</div><!-- /.filter -->

symfony/templates/hub/catalog/partials/_main.html.twig
<div class="{{ class_container|default('content') }}">
    {% include 'hub/catalog/partials/_filter.html.twig' %}

    {% if pagination|length > 0 %}
        <div class="products {{ class_container_products|default('') }}">
            {% for product in pagination %}
                {% include 'hub/catalog/partials/_box.html.twig' with {'product': product} %}
            {% endfor %}
        </div><!-- /.products -->

        {{ knp_pagination_render(pagination, 'hub/partials/sliding.html.twig') }}
    {% endif %}

</div><!-- /.content -->

symfony/templates/hub/catalog/partials/_search.html.twig
<div class="search-simple">
    <form method="get" action="{{ path('catalog') }}">
        <input type="text" id="keyword" name="keyword" class="search__field" value="{{ app.request.get('keyword', '') }}">

        <button type="submit" class="search__btn">
            <img class="svg" src="{{ asset('assets/shop/images/search.svg') }}" alt="search">
        </button>
    </form>
</div><!-- /.search-simple -->

symfony/templates/hub/catalog/partials/_sidebar.html.twig
{% if categories|length > 0 %}
    <div class="sidebar">
        <ul class="list-categories hidden-xs">

            <li {% if app.request.get('category', null) is empty %}class="current"{% endif %}><a {% if app.request.get('category', null) is empty %}style="color: #2c455b"{% endif %} href="{{ path('catalog') }}">Tous les produits</a> </li>
            {% for category in categories %}
                {% set path = path(app.request.attributes.get('_route'), app.request.attributes.get('_route_params')|merge(app.request.query.all)|merge({'category': category.id})) %}

                {% set countObj = 0 %}
                {% if categoriesCounts is defined and categoriesCounts is not empty %}
                    {% set find = false %}
                    {% for obj in categoriesCounts %}
                        {% if obj.id == category.id %}
                            {% set find = true %}
                            {% set countObj = obj.count %}
                        {% endif %}
                    {% endfor %}
                {% endif %}

                {% if countObj > 0 %}
                    <li {% if app.request.get('category', null) == category.id %}class="current" style="color: #2c455b" {% endif %}>
                        <a {% if app.request.get('category', null) == category.id %}style="color: #2c455b"{% endif %} href="{{ path }}">
                            <span>{{ category.translate('fr').name }}</span>
                            <sup style="display:inline-block;">{{ countObj }}</sup>
                        </a>
                    </li>
                {% endif %}
            {% endfor %}
        </ul>
    </div>
{% endif %}

symfony/templates/hub/catalog/partials/pagination.html.twig
{% macro simple(paginator, options) %}
    {% if paginator.haveToPaginate() %}
        {{ pagerfanta(paginator, 'custom_template', options|default({})) }}
    {% endif %}
{% endmacro %}